os:
  - osx
  - linux

language: go

go:
  - 1.8.3

go_import_path: github.com/kubernetes-incubator/external-storage

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 8192; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir -p $GOPATH/bin; fi

install:
  - curl https://glide.sh/get | sh

script:
  - make test
